steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/crown-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crown-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - crown-api
      - --image
      - gcr.io/$PROJECT_ID/crown-api
      - --region
      - us-central1
      - --allow-unauthenticated
images:
  - 'gcr.io/$PROJECT_ID/crown-api'

options:
  logging: CLOUD_LOGGING_ONLY
