steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:latest
      - --network=cloudbuild
      - --path=backend
      - --env=NPM_CONFIG_PRODUCTION=false
    id: Buildpack

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --platform=managed
      - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --add-cloudsql-instances=$_CLOUDSQL_INSTANCE
      - --env-vars-file=backend/cloudrun.env.yaml
      - --set-secrets=DB_USER=$_SECRET_DB_USER,DB_PASSWORD=$_SECRET_DB_PASSWORD,JWT_SECRET=$_SECRET_JWT_SECRET,GEMINI_API_KEY=$_SECRET_GEMINI_API_KEY
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - --region=$_DEPLOY_REGION
      - --quiet
    id: Deploy

images:
  - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: crown-api
  REPO_NAME: crown-project-clean
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _TRIGGER_ID: 3dd34c3e-1908-4f4f-9841-0c4d66c212ea
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: gen-lang-client-0711622878
  _PLATFORM: managed
  _CLOUDSQL_INSTANCE: gen-lang-client-0711622878:us-central1:crown-services-last-project-db
  _SECRET_DB_USER: db-user:latest
  _SECRET_DB_PASSWORD: db-password:latest
  _SECRET_JWT_SECRET: jwt-secret:latest
  _SECRET_GEMINI_API_KEY: gemini-api-key:latest

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - crown-api
